#!/usr/bin/env bash

docker service rm consul0 consul1

docker service create \
--name consul0 \
--network my-net \
progrium/consul -server -bootstrap-expect 3

sleep 5

docker service create \
--name consul1 \
--network my-net \
--replicas 2 \
progrium/consul -server -join consul0

sleep 10

docker service rm dkron-consul0 dkron-consul

docker service create \
--name dkron-consul0 \
--network my-net \
--publish 8090:8080 \
--container-label beta="1" \
dkron/dkron:v0.9.3-beta \
agent -server -bind=0.0.0.0:8946 -backend=consul -backend-machine=consul0:8500 -join=dkron-consul0:8946 -dog-statsd-addr=dd-agent:8125 -log-level=debug

sleep 5

docker service create \
--name dkron-consul \
--network my-net \
--replicas 5 \
--publish 8091:8080 \
--container-label beta="1" \
dkron/dkron:v0.9.3-beta \
agent -server -bind=0.0.0.0:8946 -backend=consul -backend-machine=consul0:8500 -join=dkron-consul0:8946 -dog-statsd-addr=dd-agent:8125 -log-level=debug
