#!/usr/bin/env bash

# docker service rm consul0 consul1

docker service create \
--name consul0 \
--network my-net \
progrium/consul -server -bootstrap-expect 3

sleep 5

docker service create \
--name consul1 \
--network my-net \
--replicas 2 \
progrium/consul -server -join consul0

# docker service rm dkron-consul-0 dkron-consul

docker service create \
--name dkron-consul-0 \
--network my-net \
--publish 8081:8080 \
dkron/dkron \
agent -server -bind=0.0.0.0:8946 -backend=consul -backend-machine=consul0:8500 -join=dkron-consul-0:8946 -log-level=debug

sleep 5

docker service create \
--name dkron-consul \
--network my-net \
--replicas 5 \
dkron/dkron \
agent -server -bind=0.0.0.0:8946 -backend=consul -backend-machine=consul0:8500 -join=dkron-consul-0:8946 -log-level=debug
