#!/usr/bin/env bash

for port in 8080 8090 9090
do

curl test.dkron.io:$port/v1/jobs -d '{
    "name": "test_job_1",
    "command": "/bin/true",
    "schedule": "@every 10s",
    "tags": {
        "role": "web"
    }
}'

curl test.dkron.io:$port/v1/jobs -d '{
    "name": "long_running_job_no_concurrency",
    "command": "sleep 20s",
    "schedule": "@every 15s",
    "concurrency": "forbid" 
}'

curl test.dkron.io:$port/v1/jobs -d '{
    "name": "with_dependent_job",
    "command": "/bin/true",
    "schedule": "@every 20s"
}'

curl test.dkron.io:$port/v1/jobs -d '{
    "name": "dependent_job",
    "command": "/bin/true",
    "parent_job": "with_dependent_job"
}'

curl test.dkron.io:$port/v1/jobs -d '{
    "name": "disabled_job",
    "command": "/bin/true",
    "schedule": "@every 20s",
    "disabled": true
}'
done
