#!/usr/bin/env bash

# This script is used to provision the Dkron testing infrastructure under Packet hosting
# This uses docker-machine for bootstrapping the infra using the docker-machine-packet-driver
# https://github.com/packethost/docker-machine-driver-packet
# Set PACKET_API_TOKEN env var before provisioning

# Provision the manager
# docker-machine rm manager1
docker-machine create -d packet --packet-project-id=904af849-79ff-4847-90f7-dfa02367ae72 --packet-os=ubuntu_14_04 --packet-plan=baremetal_0 --packet-facility-code=ams1 --swarm --swarm-master manager1

# Provision several workers
for i in {1..4}
do
    # docker-machine rm $i
    docker-machine create -d packet --packet-project-id=904af849-79ff-4847-90f7-dfa02367ae72 --packet-os=ubuntu_14_04 --packet-plan=baremetal_0 --packet-facility-code=ams1 --swarm worker$i &
done

#docker swarm join \
#    --token SWMTKN-1-18u9zvaz0o08jfqqr8p5bxf6fmgisjonbp55ku0lv33hlzzoz0-5q3w6vsgkkjos893mhz07aqwk \
#    10.80.76.131:2377
