#!/usr/bin/env bash

docker service rm redis0

docker service create \
--name redis0 \
--network my-net \
redis

sleep 10

docker service rm dkron-redis0 dkron-redis

docker service create \
--name dkron-redis0 \
--network my-net \
--publish 8090:8080 \
--container-label beta="0" \
dkron/dkron:v0.9.3 \
agent -server -bind=0.0.0.0:8946 -backend=redis -backend-machine=redis0:6379 -join=dkron-redis0:8946 -dog-statsd-addr=dd-agent:8125 -log-level=debug

sleep 5

docker service create \
--name dkron-redis \
--network my-net \
--replicas 5 \
--publish 8091:8080 \
--container-label beta="0" \
dkron/dkron:v0.9.3 \
agent -server -bind=0.0.0.0:8946 -backend=redis -backend-machine=redis0:6379 -join=dkron-redis0:8946 -dog-statsd-addr=dd-agent:8125 -log-level=debug
