#!/usr/bin/env bash

# docker service rm zoo1 zoo2 zoo3

docker service create \
--name zoo1 \
--network my-net \
--env ZOO_MY_ID=1 \
--env ZOO_SERVERS='server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888' \
zookeeper

docker service create \
--name zoo2 \
--network my-net \
--env ZOO_MY_ID=2 \
--env ZOO_SERVERS='server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888' \
zookeeper

docker service create \
--name zoo3 \
--network my-net \
--env ZOO_MY_ID=3 \
--env ZOO_SERVERS='server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888' \
zookeeper

# docker service rm dkron-zoo0 dkron-zoo

docker service create \
--name dkron-zoo0 \
--network my-net \
--publish 9090:8080 \
dkron/dkron \
agent -server -bind=0.0.0.0:8946 -backend=zk -backend-machine=zoo1:2181 -join=dkron-zoo0:8946 -log-level=debug

sleep 10

docker service create \
--name dkron-zoo \
--network my-net \
--replicas 5 \
--publish 9091:8080 \
dkron/dkron \
agent -server -bind=0.0.0.0:8946 -backend=zk -backend-machine=zoo1:2181 -join=dkron-zoo0:8946 -log-level=debug

# docker service create \
# --mount type=bind,source=/tmp,destination=/opt/local/dkron/config \
# --name dkron-zoo-tags \
# --network my-net \
# --replicas 5 \
# dkron/dkron \
# agent -server -bind=0.0.0.0:8946 -backend=zk -backend-machine=zoo1:2181 -join=dkron-zoo0:8946 -tag foo=bar -encrypt=kPpdjphiipNSsjd4QHWbkA== -log-level=debug
