project_name: dkron

release:
  prerelease: auto

builds:
  - &xbuild
    main: ./builtin/bins/dkron-executor-http/
    id: dkron-executor-http
    binary: dkron-executor-http
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ldflags:
      - -s -w

  - <<: *xbuild
    main: ./builtin/bins/dkron-executor-shell/
    id: dkron-executor-shell
    binary: dkron-executor-shell

  - <<: *xbuild
    main: ./builtin/bins/dkron-executor-rabbitmq/
    id: dkron-executor-rabbitmq
    binary: dkron-executor-rabbitmq

  - <<: *xbuild
    main: ./builtin/bins/dkron-executor-nats/
    id: dkron-executor-nats
    binary: dkron-executor-nats

  - <<: *xbuild
    main: ./builtin/bins/dkron-executor-kafka/
    id: dkron-executor-kafka
    binary: dkron-executor-kafka

  - <<: *xbuild
    main: ./builtin/bins/dkron-executor-gcppubsub/
    id: dkron-executor-gcppubsub
    binary: dkron-executor-gcppubsub

  - <<: *xbuild
    main: ./builtin/bins/dkron-processor-files/
    id: dkron-processor-files
    binary: dkron-processor-files

  - <<: *xbuild
    main: ./builtin/bins/dkron-processor-log/
    id: dkron-processor-log
    binary: dkron-processor-log

  - <<: *xbuild
    main: ./builtin/bins/dkron-processor-syslog/
    id: dkron-processor-syslog
    binary: dkron-processor-syslog
  
  - <<: *xbuild
    main: ./builtin/bins/dkron-processor-fluent/
    id: dkron-processor-fluent
    binary: dkron-processor-fluent

  - <<: *xbuild
    main: .
    id: dkron
    binary: dkron
    ldflags:
      - -s -w -X github.com/distribworks/dkron/v3/dkron.Version={{.Version}} -X github.com/distribworks/dkron/v3/dkron.Codename=merichuas

nfpms:
  -
    vendor: Distributed Works
    homepage: https://dkron.io
    maintainer: Victor Castell <victor@distrib.works>
    description: Distributed, fault tolerant job scheduling system
    license: LGPL 3.0

    formats:
      - deb
      - rpm

    # Override default /usr/local/bin destination for binaries
    bindir: /usr/bin

    empty_folders:
      - /var/log/dkron

    #files:
    #  "builder/files/": "/etc/init.d"
    #  "path/**/glob": "/var/foo/glob"
    config_files:
      "builder/files/dkron.yml": "/etc/dkron/dkron.yml"
      "builder/files/dkron.service": "/lib/systemd/system/dkron.service"

    overrides:
      rpm:
        replacements:
          amd64: x86_64

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^Merge pull request'
