// protoc -I proto/ --go_out=types --go_opt=paths=source_relative --go-grpc_out=types --go-grpc_opt=paths=source_relative dkron.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dkron.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Job struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Name           string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Timezone       string                   `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Schedule       string                   `protobuf:"bytes,3,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Owner          string                   `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	OwnerEmail     string                   `protobuf:"bytes,8,opt,name=owner_email,json=ownerEmail,proto3" json:"owner_email,omitempty"`
	SuccessCount   int32                    `protobuf:"varint,9,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	ErrorCount     int32                    `protobuf:"varint,10,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	Disabled       bool                     `protobuf:"varint,11,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Tags           map[string]string        `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Retries        uint32                   `protobuf:"varint,13,opt,name=retries,proto3" json:"retries,omitempty"`
	DependentJobs  []string                 `protobuf:"bytes,14,rep,name=dependent_jobs,json=dependentJobs,proto3" json:"dependent_jobs,omitempty"`
	ParentJob      string                   `protobuf:"bytes,15,opt,name=parent_job,json=parentJob,proto3" json:"parent_job,omitempty"`
	Concurrency    string                   `protobuf:"bytes,16,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Executor       string                   `protobuf:"bytes,17,opt,name=executor,proto3" json:"executor,omitempty"`
	ExecutorConfig map[string]string        `protobuf:"bytes,18,rep,name=executor_config,json=executorConfig,proto3" json:"executor_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status         string                   `protobuf:"bytes,19,opt,name=status,proto3" json:"status,omitempty"`
	Metadata       map[string]string        `protobuf:"bytes,20,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastSuccess    *Job_NullableTime        `protobuf:"bytes,25,opt,name=last_success,json=lastSuccess,proto3" json:"last_success,omitempty"`
	LastError      *Job_NullableTime        `protobuf:"bytes,26,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Next           *timestamppb.Timestamp   `protobuf:"bytes,23,opt,name=next,proto3" json:"next,omitempty"`
	Displayname    string                   `protobuf:"bytes,24,opt,name=displayname,proto3" json:"displayname,omitempty"`
	Processors     map[string]*PluginConfig `protobuf:"bytes,27,rep,name=processors,proto3" json:"processors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ephemeral      bool                     `protobuf:"varint,28,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	ExpiresAt      *Job_NullableTime        `protobuf:"bytes,29,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	StartsAt       *Job_NullableTime        `protobuf:"bytes,30,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_dkron_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *Job) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *Job) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Job) GetOwnerEmail() string {
	if x != nil {
		return x.OwnerEmail
	}
	return ""
}

func (x *Job) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *Job) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *Job) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Job) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Job) GetRetries() uint32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *Job) GetDependentJobs() []string {
	if x != nil {
		return x.DependentJobs
	}
	return nil
}

func (x *Job) GetParentJob() string {
	if x != nil {
		return x.ParentJob
	}
	return ""
}

func (x *Job) GetConcurrency() string {
	if x != nil {
		return x.Concurrency
	}
	return ""
}

func (x *Job) GetExecutor() string {
	if x != nil {
		return x.Executor
	}
	return ""
}

func (x *Job) GetExecutorConfig() map[string]string {
	if x != nil {
		return x.ExecutorConfig
	}
	return nil
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Job) GetLastSuccess() *Job_NullableTime {
	if x != nil {
		return x.LastSuccess
	}
	return nil
}

func (x *Job) GetLastError() *Job_NullableTime {
	if x != nil {
		return x.LastError
	}
	return nil
}

func (x *Job) GetNext() *timestamppb.Timestamp {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *Job) GetDisplayname() string {
	if x != nil {
		return x.Displayname
	}
	return ""
}

func (x *Job) GetProcessors() map[string]*PluginConfig {
	if x != nil {
		return x.Processors
	}
	return nil
}

func (x *Job) GetEphemeral() bool {
	if x != nil {
		return x.Ephemeral
	}
	return false
}

func (x *Job) GetExpiresAt() *Job_NullableTime {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Job) GetStartsAt() *Job_NullableTime {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

type PluginConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginConfig) Reset() {
	*x = PluginConfig{}
	mi := &file_dkron_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginConfig) ProtoMessage() {}

func (x *PluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginConfig.ProtoReflect.Descriptor instead.
func (*PluginConfig) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{1}
}

func (x *PluginConfig) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type SetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetJobRequest) Reset() {
	*x = SetJobRequest{}
	mi := &file_dkron_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetJobRequest) ProtoMessage() {}

func (x *SetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetJobRequest.ProtoReflect.Descriptor instead.
func (*SetJobRequest) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{2}
}

func (x *SetJobRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type SetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetJobResponse) Reset() {
	*x = SetJobResponse{}
	mi := &file_dkron_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetJobResponse) ProtoMessage() {}

func (x *SetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetJobResponse.ProtoReflect.Descriptor instead.
func (*SetJobResponse) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{3}
}

func (x *SetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type DeleteJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobName       string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobRequest) Reset() {
	*x = DeleteJobRequest{}
	mi := &file_dkron_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobRequest) ProtoMessage() {}

func (x *DeleteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobRequest.ProtoReflect.Descriptor instead.
func (*DeleteJobRequest) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteJobRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

type DeleteJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobResponse) Reset() {
	*x = DeleteJobResponse{}
	mi := &file_dkron_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobResponse) ProtoMessage() {}

func (x *DeleteJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobResponse.ProtoReflect.Descriptor instead.
func (*DeleteJobResponse) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobName       string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_dkron_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{6}
}

func (x *GetJobRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_dkron_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{7}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type Execution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobName       string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Output        []byte                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	NodeName      string                 `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Group         int64                  `protobuf:"varint,5,opt,name=group,proto3" json:"group,omitempty"`
	Attempt       uint32                 `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Execution) Reset() {
	*x = Execution{}
	mi := &file_dkron_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Execution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Execution) ProtoMessage() {}

func (x *Execution) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Execution.ProtoReflect.Descriptor instead.
func (*Execution) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{8}
}

func (x *Execution) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *Execution) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Execution) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Execution) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Execution) GetGroup() int64 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *Execution) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Execution) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Execution) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type ExecutionDoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *Execution             `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionDoneRequest) Reset() {
	*x = ExecutionDoneRequest{}
	mi := &file_dkron_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionDoneRequest) ProtoMessage() {}

func (x *ExecutionDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionDoneRequest.ProtoReflect.Descriptor instead.
func (*ExecutionDoneRequest) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{9}
}

func (x *ExecutionDoneRequest) GetExecution() *Execution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type ExecutionDoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionDoneResponse) Reset() {
	*x = ExecutionDoneResponse{}
	mi := &file_dkron_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionDoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionDoneResponse) ProtoMessage() {}

func (x *ExecutionDoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionDoneResponse.ProtoReflect.Descriptor instead.
func (*ExecutionDoneResponse) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{10}
}

func (x *ExecutionDoneResponse) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ExecutionDoneResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RunJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobName       string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunJobRequest) Reset() {
	*x = RunJobRequest{}
	mi := &file_dkron_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunJobRequest) ProtoMessage() {}

func (x *RunJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunJobRequest.ProtoReflect.Descriptor instead.
func (*RunJobRequest) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{11}
}

func (x *RunJobRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

type RunJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunJobResponse) Reset() {
	*x = RunJobResponse{}
	mi := &file_dkron_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunJobResponse) ProtoMessage() {}

func (x *RunJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunJobResponse.ProtoReflect.Descriptor instead.
func (*RunJobResponse) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{12}
}

func (x *RunJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type DeleteExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobName       string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExecutionsRequest) Reset() {
	*x = DeleteExecutionsRequest{}
	mi := &file_dkron_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExecutionsRequest) ProtoMessage() {}

func (x *DeleteExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExecutionsRequest.ProtoReflect.Descriptor instead.
func (*DeleteExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteExecutionsRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

type DeleteExecutionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExecutionsResponse) Reset() {
	*x = DeleteExecutionsResponse{}
	mi := &file_dkron_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExecutionsResponse) ProtoMessage() {}

func (x *DeleteExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExecutionsResponse.ProtoReflect.Descriptor instead.
func (*DeleteExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteExecutionsResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type ToggleJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobName       string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleJobRequest) Reset() {
	*x = ToggleJobRequest{}
	mi := &file_dkron_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleJobRequest) ProtoMessage() {}

func (x *ToggleJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleJobRequest.ProtoReflect.Descriptor instead.
func (*ToggleJobRequest) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{15}
}

func (x *ToggleJobRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

type ToggleJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleJobResponse) Reset() {
	*x = ToggleJobResponse{}
	mi := &file_dkron_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleJobResponse) ProtoMessage() {}

func (x *ToggleJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleJobResponse.ProtoReflect.Descriptor instead.
func (*ToggleJobResponse) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{16}
}

func (x *ToggleJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type RaftServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Leader        bool                   `protobuf:"varint,4,opt,name=leader,proto3" json:"leader,omitempty"`
	Voter         bool                   `protobuf:"varint,5,opt,name=voter,proto3" json:"voter,omitempty"`
	RaftProtocol  string                 `protobuf:"bytes,6,opt,name=raft_protocol,json=raftProtocol,proto3" json:"raft_protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftServer) Reset() {
	*x = RaftServer{}
	mi := &file_dkron_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftServer) ProtoMessage() {}

func (x *RaftServer) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftServer.ProtoReflect.Descriptor instead.
func (*RaftServer) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{17}
}

func (x *RaftServer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RaftServer) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *RaftServer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RaftServer) GetLeader() bool {
	if x != nil {
		return x.Leader
	}
	return false
}

func (x *RaftServer) GetVoter() bool {
	if x != nil {
		return x.Voter
	}
	return false
}

func (x *RaftServer) GetRaftProtocol() string {
	if x != nil {
		return x.RaftProtocol
	}
	return ""
}

type RaftGetConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*RaftServer          `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftGetConfigurationResponse) Reset() {
	*x = RaftGetConfigurationResponse{}
	mi := &file_dkron_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftGetConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftGetConfigurationResponse) ProtoMessage() {}

func (x *RaftGetConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftGetConfigurationResponse.ProtoReflect.Descriptor instead.
func (*RaftGetConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{18}
}

func (x *RaftGetConfigurationResponse) GetServers() []*RaftServer {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *RaftGetConfigurationResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type RaftRemovePeerByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftRemovePeerByIDRequest) Reset() {
	*x = RaftRemovePeerByIDRequest{}
	mi := &file_dkron_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftRemovePeerByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftRemovePeerByIDRequest) ProtoMessage() {}

func (x *RaftRemovePeerByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftRemovePeerByIDRequest.ProtoReflect.Descriptor instead.
func (*RaftRemovePeerByIDRequest) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{19}
}

func (x *RaftRemovePeerByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AgentRunStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *Execution             `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRunStream) Reset() {
	*x = AgentRunStream{}
	mi := &file_dkron_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunStream) ProtoMessage() {}

func (x *AgentRunStream) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunStream.ProtoReflect.Descriptor instead.
func (*AgentRunStream) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{20}
}

func (x *AgentRunStream) GetExecution() *Execution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type AgentRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRunResponse) Reset() {
	*x = AgentRunResponse{}
	mi := &file_dkron_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunResponse) ProtoMessage() {}

func (x *AgentRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunResponse.ProtoReflect.Descriptor instead.
func (*AgentRunResponse) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{21}
}

func (x *AgentRunResponse) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *AgentRunResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GetActiveExecutionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*Execution           `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveExecutionsResponse) Reset() {
	*x = GetActiveExecutionsResponse{}
	mi := &file_dkron_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveExecutionsResponse) ProtoMessage() {}

func (x *GetActiveExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveExecutionsResponse.ProtoReflect.Descriptor instead.
func (*GetActiveExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{22}
}

func (x *GetActiveExecutionsResponse) GetExecutions() []*Execution {
	if x != nil {
		return x.Executions
	}
	return nil
}

type AgentRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Execution     *Execution             `protobuf:"bytes,2,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRunRequest) Reset() {
	*x = AgentRunRequest{}
	mi := &file_dkron_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunRequest) ProtoMessage() {}

func (x *AgentRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunRequest.ProtoReflect.Descriptor instead.
func (*AgentRunRequest) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{23}
}

func (x *AgentRunRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *AgentRunRequest) GetExecution() *Execution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type Job_NullableTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasValue      bool                   `protobuf:"varint,1,opt,name=has_value,json=hasValue,proto3" json:"has_value,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job_NullableTime) Reset() {
	*x = Job_NullableTime{}
	mi := &file_dkron_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job_NullableTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job_NullableTime) ProtoMessage() {}

func (x *Job_NullableTime) ProtoReflect() protoreflect.Message {
	mi := &file_dkron_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job_NullableTime.ProtoReflect.Descriptor instead.
func (*Job_NullableTime) Descriptor() ([]byte, []int) {
	return file_dkron_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Job_NullableTime) GetHasValue() bool {
	if x != nil {
		return x.HasValue
	}
	return false
}

func (x *Job_NullableTime) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_dkron_proto protoreflect.FileDescriptor

const file_dkron_proto_rawDesc = "" +
	"\n" +
	"\vdkron.proto\x12\x05types\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc1\n" +
	"\n" +
	"\x03Job\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\x12\x1a\n" +
	"\bschedule\x18\x03 \x01(\tR\bschedule\x12\x14\n" +
	"\x05owner\x18\a \x01(\tR\x05owner\x12\x1f\n" +
	"\vowner_email\x18\b \x01(\tR\n" +
	"ownerEmail\x12#\n" +
	"\rsuccess_count\x18\t \x01(\x05R\fsuccessCount\x12\x1f\n" +
	"\verror_count\x18\n" +
	" \x01(\x05R\n" +
	"errorCount\x12\x1a\n" +
	"\bdisabled\x18\v \x01(\bR\bdisabled\x12(\n" +
	"\x04tags\x18\f \x03(\v2\x14.types.Job.TagsEntryR\x04tags\x12\x18\n" +
	"\aretries\x18\r \x01(\rR\aretries\x12%\n" +
	"\x0edependent_jobs\x18\x0e \x03(\tR\rdependentJobs\x12\x1d\n" +
	"\n" +
	"parent_job\x18\x0f \x01(\tR\tparentJob\x12 \n" +
	"\vconcurrency\x18\x10 \x01(\tR\vconcurrency\x12\x1a\n" +
	"\bexecutor\x18\x11 \x01(\tR\bexecutor\x12G\n" +
	"\x0fexecutor_config\x18\x12 \x03(\v2\x1e.types.Job.ExecutorConfigEntryR\x0eexecutorConfig\x12\x16\n" +
	"\x06status\x18\x13 \x01(\tR\x06status\x124\n" +
	"\bmetadata\x18\x14 \x03(\v2\x18.types.Job.MetadataEntryR\bmetadata\x12:\n" +
	"\flast_success\x18\x19 \x01(\v2\x17.types.Job.NullableTimeR\vlastSuccess\x126\n" +
	"\n" +
	"last_error\x18\x1a \x01(\v2\x17.types.Job.NullableTimeR\tlastError\x12.\n" +
	"\x04next\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\x04next\x12 \n" +
	"\vdisplayname\x18\x18 \x01(\tR\vdisplayname\x12:\n" +
	"\n" +
	"processors\x18\x1b \x03(\v2\x1a.types.Job.ProcessorsEntryR\n" +
	"processors\x12\x1c\n" +
	"\tephemeral\x18\x1c \x01(\bR\tephemeral\x126\n" +
	"\n" +
	"expires_at\x18\x1d \x01(\v2\x17.types.Job.NullableTimeR\texpiresAt\x124\n" +
	"\tstarts_at\x18\x1e \x01(\v2\x17.types.Job.NullableTimeR\bstartsAt\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13ExecutorConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a[\n" +
	"\fNullableTime\x12\x1b\n" +
	"\thas_value\x18\x01 \x01(\bR\bhasValue\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x1aR\n" +
	"\x0fProcessorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.types.PluginConfigR\x05value:\x028\x01\"\x82\x01\n" +
	"\fPluginConfig\x127\n" +
	"\x06config\x18\x01 \x03(\v2\x1f.types.PluginConfig.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\rSetJobRequest\x12\x1c\n" +
	"\x03job\x18\x01 \x01(\v2\n" +
	".types.JobR\x03job\".\n" +
	"\x0eSetJobResponse\x12\x1c\n" +
	"\x03job\x18\x01 \x01(\v2\n" +
	".types.JobR\x03job\"-\n" +
	"\x10DeleteJobRequest\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\"1\n" +
	"\x11DeleteJobResponse\x12\x1c\n" +
	"\x03job\x18\x01 \x01(\v2\n" +
	".types.JobR\x03job\"*\n" +
	"\rGetJobRequest\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\".\n" +
	"\x0eGetJobResponse\x12\x1c\n" +
	"\x03job\x18\x01 \x01(\v2\n" +
	".types.JobR\x03job\"\x9d\x02\n" +
	"\tExecution\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x03 \x01(\fR\x06output\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\x12\x14\n" +
	"\x05group\x18\x05 \x01(\x03R\x05group\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\rR\aattempt\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"F\n" +
	"\x14ExecutionDoneRequest\x12.\n" +
	"\texecution\x18\x01 \x01(\v2\x10.types.ExecutionR\texecution\"E\n" +
	"\x15ExecutionDoneResponse\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"*\n" +
	"\rRunJobRequest\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\".\n" +
	"\x0eRunJobResponse\x12\x1c\n" +
	"\x03job\x18\x01 \x01(\v2\n" +
	".types.JobR\x03job\"4\n" +
	"\x17DeleteExecutionsRequest\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\"8\n" +
	"\x18DeleteExecutionsResponse\x12\x1c\n" +
	"\x03job\x18\x01 \x01(\v2\n" +
	".types.JobR\x03job\"-\n" +
	"\x10ToggleJobRequest\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\"1\n" +
	"\x11ToggleJobResponse\x12\x1c\n" +
	"\x03job\x18\x01 \x01(\v2\n" +
	".types.JobR\x03job\"\x9d\x01\n" +
	"\n" +
	"RaftServer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x16\n" +
	"\x06leader\x18\x04 \x01(\bR\x06leader\x12\x14\n" +
	"\x05voter\x18\x05 \x01(\bR\x05voter\x12#\n" +
	"\rraft_protocol\x18\x06 \x01(\tR\fraftProtocol\"a\n" +
	"\x1cRaftGetConfigurationResponse\x12+\n" +
	"\aservers\x18\x01 \x03(\v2\x11.types.RaftServerR\aservers\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\"+\n" +
	"\x19RaftRemovePeerByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x0eAgentRunStream\x12.\n" +
	"\texecution\x18\x01 \x01(\v2\x10.types.ExecutionR\texecution\"@\n" +
	"\x10AgentRunResponse\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"O\n" +
	"\x1bGetActiveExecutionsResponse\x120\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2\x10.types.ExecutionR\n" +
	"executions\"_\n" +
	"\x0fAgentRunRequest\x12\x1c\n" +
	"\x03job\x18\x01 \x01(\v2\n" +
	".types.JobR\x03job\x12.\n" +
	"\texecution\x18\x02 \x01(\v2\x10.types.ExecutionR\texecution2\xb8\x06\n" +
	"\x05Dkron\x125\n" +
	"\x06GetJob\x12\x14.types.GetJobRequest\x1a\x15.types.GetJobResponse\x12J\n" +
	"\rExecutionDone\x12\x1b.types.ExecutionDoneRequest\x1a\x1c.types.ExecutionDoneResponse\x127\n" +
	"\x05Leave\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x125\n" +
	"\x06SetJob\x12\x14.types.SetJobRequest\x1a\x15.types.SetJobResponse\x12>\n" +
	"\tDeleteJob\x12\x17.types.DeleteJobRequest\x1a\x18.types.DeleteJobResponse\x125\n" +
	"\x06RunJob\x12\x14.types.RunJobRequest\x1a\x15.types.RunJobResponse\x12S\n" +
	"\x10DeleteExecutions\x12\x1e.types.DeleteExecutionsRequest\x1a\x1f.types.DeleteExecutionsResponse\x12>\n" +
	"\tToggleJob\x12\x17.types.ToggleJobRequest\x1a\x18.types.ToggleJobResponse\x12S\n" +
	"\x14RaftGetConfiguration\x12\x16.google.protobuf.Empty\x1a#.types.RaftGetConfigurationResponse\x12N\n" +
	"\x12RaftRemovePeerByID\x12 .types.RaftRemovePeerByIDRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x13GetActiveExecutions\x12\x16.google.protobuf.Empty\x1a\".types.GetActiveExecutionsResponse\x128\n" +
	"\fSetExecution\x12\x10.types.Execution\x1a\x16.google.protobuf.Empty2D\n" +
	"\x05Agent\x12;\n" +
	"\bAgentRun\x12\x16.types.AgentRunRequest\x1a\x15.types.AgentRunStream0\x01B,Z*github.com/distribworks/dkron/plugin/typesb\x06proto3"

var (
	file_dkron_proto_rawDescOnce sync.Once
	file_dkron_proto_rawDescData []byte
)

func file_dkron_proto_rawDescGZIP() []byte {
	file_dkron_proto_rawDescOnce.Do(func() {
		file_dkron_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dkron_proto_rawDesc), len(file_dkron_proto_rawDesc)))
	})
	return file_dkron_proto_rawDescData
}

var file_dkron_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_dkron_proto_goTypes = []any{
	(*Job)(nil),                          // 0: types.Job
	(*PluginConfig)(nil),                 // 1: types.PluginConfig
	(*SetJobRequest)(nil),                // 2: types.SetJobRequest
	(*SetJobResponse)(nil),               // 3: types.SetJobResponse
	(*DeleteJobRequest)(nil),             // 4: types.DeleteJobRequest
	(*DeleteJobResponse)(nil),            // 5: types.DeleteJobResponse
	(*GetJobRequest)(nil),                // 6: types.GetJobRequest
	(*GetJobResponse)(nil),               // 7: types.GetJobResponse
	(*Execution)(nil),                    // 8: types.Execution
	(*ExecutionDoneRequest)(nil),         // 9: types.ExecutionDoneRequest
	(*ExecutionDoneResponse)(nil),        // 10: types.ExecutionDoneResponse
	(*RunJobRequest)(nil),                // 11: types.RunJobRequest
	(*RunJobResponse)(nil),               // 12: types.RunJobResponse
	(*DeleteExecutionsRequest)(nil),      // 13: types.DeleteExecutionsRequest
	(*DeleteExecutionsResponse)(nil),     // 14: types.DeleteExecutionsResponse
	(*ToggleJobRequest)(nil),             // 15: types.ToggleJobRequest
	(*ToggleJobResponse)(nil),            // 16: types.ToggleJobResponse
	(*RaftServer)(nil),                   // 17: types.RaftServer
	(*RaftGetConfigurationResponse)(nil), // 18: types.RaftGetConfigurationResponse
	(*RaftRemovePeerByIDRequest)(nil),    // 19: types.RaftRemovePeerByIDRequest
	(*AgentRunStream)(nil),               // 20: types.AgentRunStream
	(*AgentRunResponse)(nil),             // 21: types.AgentRunResponse
	(*GetActiveExecutionsResponse)(nil),  // 22: types.GetActiveExecutionsResponse
	(*AgentRunRequest)(nil),              // 23: types.AgentRunRequest
	nil,                                  // 24: types.Job.TagsEntry
	nil,                                  // 25: types.Job.ExecutorConfigEntry
	nil,                                  // 26: types.Job.MetadataEntry
	(*Job_NullableTime)(nil),             // 27: types.Job.NullableTime
	nil,                                  // 28: types.Job.ProcessorsEntry
	nil,                                  // 29: types.PluginConfig.ConfigEntry
	(*timestamppb.Timestamp)(nil),        // 30: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 31: google.protobuf.Empty
}
var file_dkron_proto_depIdxs = []int32{
	24, // 0: types.Job.tags:type_name -> types.Job.TagsEntry
	25, // 1: types.Job.executor_config:type_name -> types.Job.ExecutorConfigEntry
	26, // 2: types.Job.metadata:type_name -> types.Job.MetadataEntry
	27, // 3: types.Job.last_success:type_name -> types.Job.NullableTime
	27, // 4: types.Job.last_error:type_name -> types.Job.NullableTime
	30, // 5: types.Job.next:type_name -> google.protobuf.Timestamp
	28, // 6: types.Job.processors:type_name -> types.Job.ProcessorsEntry
	27, // 7: types.Job.expires_at:type_name -> types.Job.NullableTime
	27, // 8: types.Job.starts_at:type_name -> types.Job.NullableTime
	29, // 9: types.PluginConfig.config:type_name -> types.PluginConfig.ConfigEntry
	0,  // 10: types.SetJobRequest.job:type_name -> types.Job
	0,  // 11: types.SetJobResponse.job:type_name -> types.Job
	0,  // 12: types.DeleteJobResponse.job:type_name -> types.Job
	0,  // 13: types.GetJobResponse.job:type_name -> types.Job
	30, // 14: types.Execution.started_at:type_name -> google.protobuf.Timestamp
	30, // 15: types.Execution.finished_at:type_name -> google.protobuf.Timestamp
	8,  // 16: types.ExecutionDoneRequest.execution:type_name -> types.Execution
	0,  // 17: types.RunJobResponse.job:type_name -> types.Job
	0,  // 18: types.DeleteExecutionsResponse.job:type_name -> types.Job
	0,  // 19: types.ToggleJobResponse.job:type_name -> types.Job
	17, // 20: types.RaftGetConfigurationResponse.servers:type_name -> types.RaftServer
	8,  // 21: types.AgentRunStream.execution:type_name -> types.Execution
	8,  // 22: types.GetActiveExecutionsResponse.executions:type_name -> types.Execution
	0,  // 23: types.AgentRunRequest.job:type_name -> types.Job
	8,  // 24: types.AgentRunRequest.execution:type_name -> types.Execution
	30, // 25: types.Job.NullableTime.time:type_name -> google.protobuf.Timestamp
	1,  // 26: types.Job.ProcessorsEntry.value:type_name -> types.PluginConfig
	6,  // 27: types.Dkron.GetJob:input_type -> types.GetJobRequest
	9,  // 28: types.Dkron.ExecutionDone:input_type -> types.ExecutionDoneRequest
	31, // 29: types.Dkron.Leave:input_type -> google.protobuf.Empty
	2,  // 30: types.Dkron.SetJob:input_type -> types.SetJobRequest
	4,  // 31: types.Dkron.DeleteJob:input_type -> types.DeleteJobRequest
	11, // 32: types.Dkron.RunJob:input_type -> types.RunJobRequest
	13, // 33: types.Dkron.DeleteExecutions:input_type -> types.DeleteExecutionsRequest
	15, // 34: types.Dkron.ToggleJob:input_type -> types.ToggleJobRequest
	31, // 35: types.Dkron.RaftGetConfiguration:input_type -> google.protobuf.Empty
	19, // 36: types.Dkron.RaftRemovePeerByID:input_type -> types.RaftRemovePeerByIDRequest
	31, // 37: types.Dkron.GetActiveExecutions:input_type -> google.protobuf.Empty
	8,  // 38: types.Dkron.SetExecution:input_type -> types.Execution
	23, // 39: types.Agent.AgentRun:input_type -> types.AgentRunRequest
	7,  // 40: types.Dkron.GetJob:output_type -> types.GetJobResponse
	10, // 41: types.Dkron.ExecutionDone:output_type -> types.ExecutionDoneResponse
	31, // 42: types.Dkron.Leave:output_type -> google.protobuf.Empty
	3,  // 43: types.Dkron.SetJob:output_type -> types.SetJobResponse
	5,  // 44: types.Dkron.DeleteJob:output_type -> types.DeleteJobResponse
	12, // 45: types.Dkron.RunJob:output_type -> types.RunJobResponse
	14, // 46: types.Dkron.DeleteExecutions:output_type -> types.DeleteExecutionsResponse
	16, // 47: types.Dkron.ToggleJob:output_type -> types.ToggleJobResponse
	18, // 48: types.Dkron.RaftGetConfiguration:output_type -> types.RaftGetConfigurationResponse
	31, // 49: types.Dkron.RaftRemovePeerByID:output_type -> google.protobuf.Empty
	22, // 50: types.Dkron.GetActiveExecutions:output_type -> types.GetActiveExecutionsResponse
	31, // 51: types.Dkron.SetExecution:output_type -> google.protobuf.Empty
	20, // 52: types.Agent.AgentRun:output_type -> types.AgentRunStream
	40, // [40:53] is the sub-list for method output_type
	27, // [27:40] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_dkron_proto_init() }
func file_dkron_proto_init() {
	if File_dkron_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dkron_proto_rawDesc), len(file_dkron_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_dkron_proto_goTypes,
		DependencyIndexes: file_dkron_proto_depIdxs,
		MessageInfos:      file_dkron_proto_msgTypes,
	}.Build()
	File_dkron_proto = out.File
	file_dkron_proto_goTypes = nil
	file_dkron_proto_depIdxs = nil
}
