#!/usr/bin/env bash

set -e
set -o pipefail
docker build -t dkron .
docker run dkron scripts/validate-gofmt
docker run dkron go vet
docker run --rm dkron go test -v ./... $1  | sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' | sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/''
