#!/usr/bin/env bash
docker build -t dkron .
docker run dkron scripts/validate-gofmt
docker run dkron go vet
docker run --rm --name etcd -d -p "2379" quay.io/coreos/etcd etcd -name=dkron1 -advertise-client-urls http://etcd:2379 -listen-client-urls http://0.0.0.0:2379
docker run --link etcd -e DKRON_BACKEND_MACHINE=etcd:2379 dkron go test -v ./... $1
docker kill etcd
