#!/usr/bin/env bash

read -r -d '' NOVENDOR << EOM
./builtin/...
./cron/...
./dkron/...
./plugin/...
.
EOM

docker-compose run dkron scripts/validate-gofmt
docker-compose run dkron go vet $NOVENDOR
docker-compose run -e DKRON_BACKEND_MACHINE=consul:8500 dkron go test -v $NOVENDOR $1
