name: Test
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

  pull_request:
    paths-ignore:
      - '**.md'
      - 'website/**'
      - 'docs/**'
      - 'examples/**'
      - 'ui'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test without docker
        run: go test -v -timeout 200s ./...
